### ISSUE TITLE
Allow docker daemon connection via TCP

### ISSUE THREAD

**Issue by gymnae** [BigBoot/AutoKuma#10]
Great initiative :)

I'm running the uptime-kuma stack on an LXC container outside of my VM running all the heavy lifting for my docker infrastructure.
Thus I cannot connect to the unix socket, but I exposed the daemon on my local network via TCP.
Uptime-kuma can see and connect to this TCP socket, but auto-kuma throws this error:

`autokuma::sync > Encountered error during sync: error trying to connect: No such file or directory (os error 2)`

I start the container like this:
```
docker run -d \
        --restart=always \
        -e AUTOKUMA__KUMA__URL=http://localhost:3001 \
        -e AUTOKUMA__KUMA__USERNAME=<user>\
        -e AUTOKUMA__KUMA__PASSWORD=<password> \
        -e AUTOKUMA__KUMA__DOCKER__SOCKET=http://<docker host>:2375  \
        --network host \
        --name autokuma \
        --hostname autokuma \
        ghcr.io/bigboot/autokuma:latest
```

**Comment by BigBoot** [comment]
I've added a fallback to the DOCKER_HOST env variable when no docker socket is specified, so this should now work 

```
docker run -d \
        --restart=always \
        -e AUTOKUMA__KUMA__URL=http://localhost:3001 \
        -e AUTOKUMA__KUMA__USERNAME=<user>\
        -e AUTOKUMA__KUMA__PASSWORD=<password> \
        -e DOCKER_HOST=http://<docker host>:2375  \
        --network host \
        --name autokuma \
        --hostname autokuma \
        ghcr.io/bigboot/autokuma:master
```
