### ISSUE TITLE
JSON Static Configs with Multiple Objects not working - Unable to deserialize: Not an object

### ISSUE THREAD

**Issue by cmacnichol** [BigBoot/AutoKuma#107]
I have been attempting to use the file provider to create static alerts for multiple groups and services in a single file. Using the Example Multiple Object JSON from the Repository gives me the exact same error as my JSON below.  Not really sure what is going on. Has the JSON format changed?

`WARN [autokuma::sync] Encountered error during sync: Unable to deserialize: Not an object`

`[
    {
        "description": "All DNS Servers",
        "name": "ADGuard",
        "type": "group"
    },
    {
        "description": "All IP Cameras",
        "name": "Cameras",
        "type": "group"
    }
]`

**Comment by cmacnichol** [comment]
Well, that explains a lot.  Thanks for the fast response on this.

Just switched my container to that after backing it up and the JSON is now working correctly.  Are any other parameters supported for options or notifications in the JSON format?

**Comment by BigBoot** [comment]
I'm not sure if I understand that correctly, are you looking for https://github.com/BigBoot/AutoKuma/blob/master/ENTITY_TYPES.md ?

**Comment by cmacnichol** [comment]
Yep, that was exactly what I was looking for.  Did not see it linked on the main page anywhere, or I just missed it.  

Thanks for the help and for all the effort in developing this.  It makes Kuma so much more dynamic.
