### ISSUE TITLE
Static monitor for groups

### ISSUE THREAD

**Issue by jordanlambrecht** [BigBoot/AutoKuma#15]
If I create a static group monitor, how would I define its ID so other containers can use it?

i.e
```
{
     "name": "Test Group",
     "type": "group",
     "id": "testgroup",
     "active": true
}
```

**Comment by BigBoot** [comment]
In case of static monitors the filename is the id, so if the file is called "testgroup.json" the id is "testgroup".

**Comment by jordanlambrecht** [comment]
Oh dope. Thanks a bunch.

**Comment by AurimasNav** [comment]
> In case of static monitors the filename is the id, so if the file is called "testgroup.json" the id is "testgroup".

how do you reference this id in another static monitor? `parent` seems to accept i32 only?
> WARN [autokuma::sync] Encountered error during sync: Error while trying to parse labels: Unable to parse connectivity-group as i32
