### ISSUE TITLE
Push monitor type URL format

### ISSUE THREAD

**Issue by radokristof** [BigBoot/AutoKuma#21]
What is the correct syntax for the push monitor type `push_url` parameter?
It seems if I leave it out, there will be no ID for that monitor (ID will be null) and it will get regenerated every time when opening that monitor.
I tried setting a few value for it, but none of them seemed to work.

**Comment by BigBoot** [comment]
Hmm looks like push monitor will need some special treatment, I'll take a look late today.

**Comment by BigBoot** [comment]
It's now possible to specify a push_token, the token has to be 32 characters long and consist of `[a-zA-Z0-9]`

**Comment by radokristof** [comment]
Thank you :)
