### ISSUE TITLE
Case customization possible?

### ISSUE THREAD

**Issue by undaunt** [BigBoot/AutoKuma#27]
Similar to ansible, would it be possible to support modifications to {{container_name}} such as {{container_name|upper}} or {{container_name|title}}?

Eg: for container named portainer:

{{container_name}} : portainer
{{container_name|title}} : Portainer
{{container_name|upper}} : PORTAINER

Thank you. I wasn't sure if this was something you were leveraging from either the compose specification or it was written into Autokuma. I am not a developer. Sorry if this is a dumb question.

**Comment by BigBoot** [comment]
This is currently not possible as I'm doing a simple search and replace, I've though about switching this out with a fully fledged template engine, but this would end up being a breaking change so I've been hesitant for now.

**Comment by BigBoot** [comment]
This is now available on master, please check the CHANGELOG.md as wells as [Tera Documentation](https://keats.github.io/tera/docs/)
