### ISSUE TITLE
static checks should support recursive dirs

### ISSUE THREAD

**Issue by johntdyer** [BigBoot/AutoKuma#28]
I might want to organize my static checks in folders but the feature currently doesnt support recursive search into folders.  This would be a nice thing to have

**Comment by johntdyer** [comment]
FWIW I now get this error, which I think is new for 0.6.0

```
WARN [autokuma::sync] Encountered error during sync: Unable to deserialize: Unsupported static monitor file type: /static/adsb, supported: .json, .toml
WARN [autokuma::sync] Encountered error during sync: Unable to deserialize: Unsupported static monitor file type: /static/adsb, supported: .json, .toml
WARN [autokuma::sync] Encountered error during sync: Unable to deserialize: Unsupported static monitor file type: /static/adsb, supported: .json, .toml
WARN [autokuma::sync] Encountered error during sync: Unable to deserialize: Unsupported static monitor file type: /static/adsb, supported: .json, .toml
WARN [autokuma::sync] Encountered error during sync: Unable to deserialize: Unsupported static monitor file type: /static/adsb, supported: .json, .toml
WARN [autokuma::sync] Encountered error during sync: Unable to deserialize: Unsupported static monitor file type: /static/adsb, supported: .json, .toml
```

**Comment by BigBoot** [comment]
Yes, static monitors still do not support recursive search, I'm hesitant to add this because the filename is used as the id and i'm not sure something like "<dir>/<filename>" would be a good fit for the id

**Comment by BigBoot** [comment]
This has been fixed on master, please note that the master currently contains some breaking change so make sure to read the [CHANGELOG](https://github.com/BigBoot/AutoKuma/blob/master/CHANGELOG.md#unreleased) if you want to test the feature.
