### ISSUE TITLE
Disable Auto-Deleting Monitors

### ISSUE THREAD

**Issue by reedhaffner** [BigBoot/AutoKuma#29]
I had some unexpected behavior when trying to test out my alerting.

I have AutoKuma adding a very basic Docker container monitor, with just the `docker_container`, `docker_host`, and `docker.name` being set.

I went to a container tagged to be pulled into UptimeKuma and I ran `docker compose down` to cause the monitor to see it as down. However, when I ran the down command, AutoKuma immediately removed the monitor from UptimeKuma.

I'm not sure if this is expected due to the container labels being removed. I think it would be great to have a boolean setting to disable auto-removing monitors, and only run create and update.

**Comment by BigBoot** [comment]
This can now be configured using the `on_delete` config
