### ISSUE TITLE
volumes support in compose.yaml for mapping a custom autokuma config folder?

### ISSUE THREAD

**Issue by mgrimace** [BigBoot/AutoKuma#30]
Hi, thanks for this, my question/request is is there volume mapping support for docker compose to specify where we want the config?
For example, for uptime-kuma I use:
```yaml
    volumes:
      - ${DOCKERDIR}/appdata/uptime-kuma/data:/app/data
```
If I've missed this I apologize in advance, I'm a novice and I didn't see it in the documentation or the sample compose and it appears that the config.toml is expected to be found in a fixed location.

**Comment by BigBoot** [comment]
Hi, there's really no reason to mount any volume (besides maybe the logs dir if you use that feature). Autokuma does not store anything as of now and the settings are all available using env variables.

**Comment by mgrimace** [comment]
Thanks ok, appreciate that!

**Comment by joshward9182** [comment]
@BigBoot TLDR: where can I expect to put config.toml in a docker container install?


I am installed by Docker on Unraid.

I am trying to set up some snippets but large, multiline label values don't really play nice in Unraid, so I was hoping to use the config.toml.

I've tried it in a few places, like '/config.toml', as it doesn't seem clear to me in the documentation. No matter where I put it, the logs say snippet not found.

Any help would be appreciated 🙂

**Comment by maddox** [comment]
I'm running into this same issue. Where do we put the config file? The README only mentions OS's as if we're running them directly on the host, vs docker.

**Comment by nemchik** [comment]
Sorry to necro this, but my question is kind of the same for a different reason. I want to use snippets in `config.toml` that are multi-line, and unraid doesn't do well handling multi-line labels. I'm not entirely sure where the file should be in order for autokuma to pick it up though.

I also notice https://autokuma.bigboot.dev/dev/autokuma/configuration/#config-file mentions both `autokuma.toml` and `config.toml` so I'm not sure which one is correct. Also, the `$XDG_CONFIG_HOME/autokuma/config.{toml,yaml,json}` path is a bit confusing with regards to using a docker container, because `echo "$XDG_CONFIG_HOME"` from a shell inside the container doesn't seem to have a value.

@BigBoot any insight on this?

**Comment by BigBoot** [comment]
@nemchik 

Autokuma supports loading config files from multiple locations, the $XDG_CONFIG_HOME is indeed more intended for a "normal" installation e.g. on a rpi or something. That said it can be used in a container, you'd end up with the following path: `/root/.config/autokuma/config.toml` if running as root.

For docker setups the intended way is to use the `autokuma.conf` file loaded from the current working dir. By default in the container this is `/`, so the full path would be `/autokuma.conf`. The cwd can also be overriden e.g. with the compose setting `working_dir` or the `-w` flag in plan docker.

**Comment by nemchik** [comment]
Thanks for the reply. I was able to get it working by making a volume for the file `/mnt/user/appdata/autokuma/autokuma.toml:/autokuma.toml`

Note for any future readers: you have to create the file first or docker will create the host path as a folder. This applies to unraid as well.

This seems to be working the way I want it now.

I set up multiple snippets:

```toml
[snippets]
docker = '''
  {{container_name}}.group.name: {{container_name}}
  {{container_name}}_docker.docker.parent_name: {{container_name}}
  {{container_name}}_docker.docker.name: {{container_name}} Docker
  {{container_name}}_docker.docker.docker_container: {{container_name}}
  {{container_name}}_docker.docker.docker_host_name: unraid
  unraid.docker_host.name: unraid
  unraid.docker_host.connection_type: socket
  unraid.docker_host.path: /var/run/docker.sock
'''

http_local = '''
  {{container_name}}.group.name: {{container_name}}
  {{container_name}}_http_local.http.parent_name: {{container_name}}
  {{container_name}}_http_local.http.name: {{container_name}} HTTP Local
  {{container_name}}_http_local.http.url: {{args[0]}}
'''

http_proxy = '''
  {{container_name}}.group.name: {{container_name}}
  {{container_name}}_http_proxy.http.parent_name: {{container_name}}
  {{container_name}}_http_proxy.http.name: {{container_name}} HTTP Proxy
  {{container_name}}_http_proxy.http.url: {{args[0]}}
'''
```

And now for each container I add labels if the snippet applies.

For me:

- `kuma.__docker: "any-value"`
  - All containers get this label. The value has to be in quotes. Even though it doesn't use any args it has to have a value in the quotes.
- `kuma.__http_local: "http://container-name:port/"`
  - Containers with a web UI get this label. I don't use variables in the labels. This is an internal check to make sure the service inside the container is actually running, not just that the container is running.
- `kuma.__http_proxy: "https://container-proxy-url.mydomain.com/"`
  - Containers that I proxy get this label. Again, not using variables in the labels. This is making sure that the service is reachable through the proxy.

This is super convenient compared to trying to keep up with all of the labels it would have required on each container without snippets.
