### ISSUE TITLE
Basic Auth Question

### ISSUE THREAD

**Issue by undaunt** [BigBoot/AutoKuma#46]
I see that auth_method and basic_auth_user are available in the monitor types document. Two questions:

1 - Would auth_method auto translate to the authMethod listed within kuma cli? 
![image](https://github.com/BigBoot/AutoKuma/assets/31376520/6374e95f-a3e8-4479-bafd-526b38e6bb17)

2 - Are we able to pass basic auth passwords, or only users?

Thanks!

**Comment by BigBoot** [comment]
Hi, yes there is `basic_auth_user` and `basic_auth_pass`, as well as `authMethod` available, generally speaking autokuma will accept snake_case as well as whatever case uptime kuma is using for that parameter. (Although for technical reasons snake_case is not possible for `authMethod`)

**Comment by undaunt** [comment]
I may have written this incorrectly, but I'm currently getting:

```
05/29/2024 04:04:25 PM WARN [kuma_client::util] Invalid snippet line: '    resilio-sync-http.http.authMethod = basic'
05/29/2024 04:04:25 PM WARN [kuma_client::util] Invalid snippet line: '    resilio-sync-http.http.basic_auth_user = undaunt'
05/29/2024 04:04:25 PM WARN [kuma_client::util] Invalid snippet line: '    resilio-sync-http.http.basic_auth_pass = xxxxxxxx'
```

Snippet portion:

```
          {% if args.auth and args.auth == "basic" %}
            {{ id }}-http.http.authMethod = {{ args.auth }}
            {{ id }}-http.http.basic_auth_user = {{ args.auth_user }}
            {{ id }}-http.http.basic_auth_pass = {{ args.auth_pass }}
          {% endif %}
```

Container label:

`kuma.__app: '{ "name": "Resilio Sync", "type": "web", "url": "https://${SUBDOMAIN_RESILIO}.${DOMAINNAME}", "internal_port": "8888", "auth": "basic", "auth_user": "${RESILIO_USER}", "auth_pass": "${RESILIO_PASSWORD}" }'`

**Comment by undaunt** [comment]
Closing, realized I declared with = not a colon
