### ISSUE TITLE
Format for multiple tags for a static monitor?

### ISSUE THREAD

**Issue by zodac** [BigBoot/AutoKuma#51]
I am trying to add a static monitor and specify multiple tags. I can get it working fine with a single tag:

```
name = "Site"
url = "my.url"
type = "http"
tags = '[{"tag_id": 1 }]'
```

However, when I try and use 2 tags, I get the following error:

```
name = "Site"
url = "my.url"
type = "http"
tags = [{"tag_id" = 1},{"tag_id" = 2}]
```

> WARN [autokuma::sync] Encountered error during sync: Error while trying to parse labels: expected `:` at line 1 column 27

I tried with JSON too, and got a different bad syntax error:

```
{
  "name": "Site",
  "type": "http",
  "url": "my.url",
  "tags": [
    {
      "tag_id": 1
    },
    {
      "tag_id": 2
    }
  ]
}
```

This gave the error:

> WARN [autokuma::sync] Encountered error during sync: Error while trying to parse labels: TOML parse error at line 8, column 18
>    |
>  8 | tags = [{"tag_id":1},{"tag_id":2}]
>    |                  ^
>  expected `.`, `=`

Apologies if I missed an example, I wasn't able to find one in the docs or previous issues.

**Comment by BigBoot** [comment]
Hi, due to autokuma normally getting it's values from docker labels nested arrays need to be passed as a string and formatted as json. So this should work:

Toml:
```toml
name = "Site"
url = "my.url"
type = "http"
tags = '[{"tag_id": 1},{"tag_id": 2}]'
```

Json:
```json
{
  "name": "Site",
  "type": "http",
  "url": "my.url",
  "tags":  "[{\"tag_id\": 1},{\"tag_id\": 2}]"
}
```

**Comment by zodac** [comment]
Thanks, that did the job! :)
