### ISSUE TITLE
More docs on static monitors (examples)

### ISSUE THREAD

**Issue by AurimasNav** [BigBoot/AutoKuma#75]
I'm struggling to figure out how to define static monitors/groups or what is and what isn't possible.

- It seems creating monitors generates random ids, so there is no way to define monitors with a group in advance?
- is there a way to create status pages?

Basically I would like to create few monitors, add them to a group, create a status page for them and setup notifications.
Which of these parts are possible via autokuma ?

(not running on docker, therefore only using static monitors)

**Comment by BigBoot** [comment]
Hi, as you already found out for static monitors the filenames are the ids used by autokuma, note that these are not the same as the numerical ids assigned by uptime kuma. 

To allow assigning groups autokuma adds the special property "parent_name" to all monitor types, this is used to resolve a monitor by the autokuma id (i.e. your filename).

so something like this would work:

my_group.json
```json
{
  "type": "group",
  "name": "My Group"
}
```

my_child_monitor.json
```json
{
  "type": "http",
  "parent_name": "my_group",
  "url": "https://example.com"
}
```

Please also note that autokuma itself currently cannot create status pages and/or notifications providers, they can however be created using the kuma CLI.
