### ISSUE TITLE
"enum DockerSource does not have variant constructor xxxx"  due to Documentation !!! 

### ISSUE THREAD

**Issue by UnclePhil** [BigBoot/AutoKuma#79]
In your doc 
you say 
```
AUTOKUMA__DOCKER__SOURCE | docker.source | Wether monitors should be created from container or service labels (or both).
```

I receive a lot of these error

> Invalid config: enum DockerSource does not have variant constructor service

when i use 
AUTOKUMA__DOCKER__SOURCE: service

and when i use 
AUTOKUMA__DOCKER__SOURCE: container

> Invalid config: enum DockerSource does not have variant constructor container

But none when I remove the line 

**And none after reading your source code** 
where you use  
- "Services" 
- "Containers"
- "Both" 

**PLEASE update your documentation ... 
or your code to reflect it**

**Comment by BigBoot** [comment]
Hmm looks like this is a limitation of the config library I'm using, the aliasing doesn't work for all config sources, I've updated the documentation to use the non aliased values.
