### ISSUE TITLE
how to add multiple sites on the static monitors toml/json file?

### ISSUE THREAD

**Issue by lazyzyf** [BigBoot/AutoKuma#86]
or I can only create one toml/json file for each url?

**Comment by BigBoot** [comment]
Yes, it's one file per monitor

**Comment by lazyzyf** [comment]
Can you please improve it to be able to parse multiple monitors in one file?

**Comment by BigBoot** [comment]
This is now possible on master, see [multi_example.json](https://github.com/BigBoot/AutoKuma/blob/master/monitors/multi_example.json), please note that the master currently contains some breaking change so make sure to read the [CHANGELOG](https://github.com/BigBoot/AutoKuma/blob/master/CHANGELOG.md#unreleased) if you want to test the feature.
