### ISSUE TITLE
UptimeKuma v2 condition error

### ISSUE THREAD

**Issue by barcar** [BigBoot/AutoKuma#98]
When using this with UptimeKuma v2 I am getting errors on creation…

WARN [autokuma::sync] Encountered error during sync: Server responded with an error: insert into `monitor` (`accepted_statuscodes_json`, `conditions`, `docker_container`, `interval`, `kafka_producer_brokers`, `kafka_producer_sasl_options`, `maxretries`, `name`, `parent`, `rabbitmq_nodes`, `retry_interval`, `type`, `user_id`) values ('["200-299"]', NULL, 'monitoring-autokuma-1', 60, NULL, NULL, 3, '"AutoKuma"', NULL, NULL, 60, 'docker', 1) - SQLITE_CONSTRAINT: NOT NULL constraint failed: monitor.conditions

It seems that the “conditions” value cannot be null.

is v2 supported? Is there a way to set “conditions” to an appropriate value?

**Comment by BigBoot** [comment]
See #99
